cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'git'
brew 'tmux'
brew 'tmux-cssh'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'libxmlsec1'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'ripgrep'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'htop'
brew 'vim'
brew 'nvm'
brew 'awscli'

cask 'dropbox'
cask '1password'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'vlc'
cask 'spotify'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'gpgtools'
cask 'virtualbox'
cask 'keycastr'
cask 'screenhero'
cask 'flux'
cask 'keybase'
cask 'xquartz'
cask 'brave'
cask 'tunnelbear'
