tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

cask "xquartz"

brew "ack"
brew "awscli"
brew "bat"
brew "coreutils"
brew "exa"
brew "fd"
brew "git"
brew "go"
brew "grc"
brew "htop"
brew "httpie"
brew "jq"
brew "libgit2"
brew "libxmlsec1"
brew "llvm"
brew "mas"
brew "nvm"
brew "procs"
brew "ripgrep"
brew "roundup"
brew "spaceman-diff"
brew "spark"
brew "vim"
brew "wget"

cask "1password"
cask "visual-studio-code"
cask "android-sdk"
cask "atom"
cask "brave-browser"
cask "dropbox"
cask "firefox"
cask "font-inconsolatalgc-nerd-font"
cask "font-victor-mono"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keybase"
cask "keycastr"
cask "screenhero"
cask "signal"
cask "slack"
cask "spotify"

mas "Amphetamine", id: 937984704
mas "Frank DeLoupe", id: 530458789
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
